spring:
  application:
    name: mdm
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  liquibase:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: mysecretpassword
    change-log: classpath:db/db.changelog-master.xml
    enabled: true
    default-schema: public
springdoc:
  api-docs:
    path: /api-docs
